name: Java Testing

on:
    push:
        branches:
          - '*'
    pull_request:
        branches:
          - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew
      - name: Run Gradle test
        run: ./gradlew test