name: Java Testing

on:
    push:
        branches:
          - '*'
    pull_request:
        branches:
          - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create the output directory
      run: mkdir -p out/production/

    - name: Download JUnit 5 Console Launcher
      run: wget -P lib/ https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar

    - name: Compile Source Files
      run: |
        javac -d out/production/ -cp "lib/*" $(find ./src -name "*.java")

    - name: Compile Test Files
      run: |
        javac -d out/production/ -cp out/production/:lib/* $(find ./test -name "*Test.java")

    - name: Run JUnit Tests
      run: |
        java -jar lib/junit-platform-console-standalone-1.9.3.jar --class-path out/production/:lib/* --scan-classpath